name: MultimoduleSample
options:
  bundleIdPrefix: taichi.com.multimoduleSample
  minimumXcodeGenVersion: 2.41.0
  xcodeVersion: 16.1
  deploymentTarget:
    iOS: 17.0
  groupOrdering:
    - order: [MainApp, HogeFeature, Core, TestHogeFeature, UITest]
configs:
  Debug: debug
  AppStore: release
settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1.0.0
    CODE_SIGN_STYLE: Automatic
    # Swiftのバージョン
    SWIFT_VERSION: 6.0
    # Info.plistがなければ自動で生成する
    GENERATE_INFOPLIST_FILE: YES
    # 以降の設定はXcode14のデフォルト設定
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    GCC_DYNAMIC_NO_PIC: NO
    GCC_NO_COMMON_BLOCKS: YES
    GCC_C_LANGUAGE_STANDARD: gnu17
    CLANG_CXX_LANGUAGE_STANDARD: gnu++20
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ENABLE_MODULE_VERIFIER: YES
  configs:
    debug:
      # ビルド成果物の最適化は行わずビルド速度を優先する
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      # 以降の設定はXcode14のデフォルト設定
      VALIDATE_PRODUCT: NO
      GCC_OPTIMIZATION_LEVEL: "0"
    appstore:
      # ビルド速度は落ちるが、ビルド成果物の最適化を行う
      SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
      # 以降の設定はXcode14のデフォルト設定
      VALIDATE_PRODUCT: YES
      GCC_OPTIMIZATION_LEVEL: "s"
targets:
  MainApp:
    type: application
    platform: iOS
    sources: [MainApp]
    settings:
      base:
        INFOPLIST_FILE: MainApp/Info.plist
        DEVELOPMENT_ASSET_PATHS: MainApp/PreviewContent
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
    info:
      path: MainApp/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES # iOSで実行する必要がある旨の設定
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES # アプリが一般的に間接入力メカニズムをサポートしていることを示すブール値(https://qiita.com/tamadeveloper/items/4be3c7e410831d2d5a4e)
        UISupportedInterfaceOrientations~iphone:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
    dependencies:
      - target: HogeFeature
  HogeFeature:
    type: framework
    platform: iOS
    sources: [HogeFeature]
    dependencies:
      - target: Core
  Core:
    type: framework
    platform: iOS
    sources: [Core]
  TestHogeFeature:
    type: bundle.unit-test
    platform: iOS
    sources: [TestHogeFeature]
    dependencies:
      - target: HogeFeature
  UITest:
    type: bundle.ui-testing
    platform: iOS
    sources: [UITest]
    dependencies:
      - target: MainApp
schemes:
  MainApp:
    build:
      targets:
        MainApp: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets: all
      targets:
        - name: TestHogeFeature
          parallelizable: true
          randomExecutionOrder: true
        - name: UITest
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: AppStore
    analyze:
      config: Debug
    archive:
      config: AppStore
  HogeFeature:
    templates:
      - FeatureModuleScheme
    templateAttributes:
      testTargetName: TestHogeFeature
schemeTemplates:
  FeatureModuleScheme:
    templates:
      - TestScheme
    build:
      targets:
        ${scheme_name}: all
  TestScheme:
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets: all
      targets:
        - name: ${testTargetName}
          parallelizable: true
          randomExecutionOrder: true
