name: MultimoduleSample
options:
  bundleIdPrefix: taichi.com.multimoduleSample
  minimumXcodeGenVersion: 2.41.0
  xcodeVersion: 16.1
  deploymentTarget:
    iOS: 17.0
  groupOrdering:
    - order: [MainApp, HomeFeature, Core]
configs:
  Debug: debug
  AppStore: release
settings:
  base:
    DEVELOPMENT_TEAM: "stotic-dev"
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1.0.0
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: 6.0
    CLANG_CXX_LANGUAGE_STANDARD: gnu++17
targets:
  MainApp:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    sources: [MainApp]
    settings:
      base:
        INFOPLIST_FILE: MainApp/Info.plist
    info:
      path: MainApp/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES # iOSで実行する必要がある旨の設定
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES # アプリが一般的に間接入力メカニズムをサポートしていることを示すブール値(https://qiita.com/tamadeveloper/items/4be3c7e410831d2d5a4e)
        UISupportedInterfaceOrientations~iphone:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
    dependencies:
      - target: HomeFeature
      - target: Core
  HomeFeature:
    type: framework
    platform: iOS
    supportedDestinations: [iOS]
    sources: [HomeFeature]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        MACH_O_TYPE: staticlib
    dependencies:
      - target: Core
  Core:
    type: framework
    platform: iOS
    sources: [Core]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
